### ISSUE TITLE
war not deploying idega

### ISSUE THREAD

**Issue by dhirajgraycelltech** [idega/com.idega.core#3]
hi All, i have build the war for idega project by follow all the step of (get started guide) idega, but when i deploying it using tomcat, when i hit the url with war name, that is something ending with SNAPSHOT then it says no resource found, now i don't know the next step to deploy the war. Now, i have not found anything that will helpful, given in the idega website copyright 2009. Also web.xml of project is empty, i don't why it is like this. Plz give me the right way to doing it.

**Comment by L4p1n45** [comment]
Hello,

You need to fetch and compile in order from BRANCH_PLATFORM_5: 
https://github.com/idega/com.idega.block.platform;
https://github.com/idega/com.idega.block.addon;
https://github.com/idega/com.idega.maven.webapp;
https://github.com/idega/lucid;

You should use this context in Tomcat 7:
<Context
	path=""
	docBase="{some_directory}/lucid/target/lucid-5.0.0-SNAPSHOT"
	reloadable="true"
	debug="0">
	<Resource
		name="jdbc/DefaultDS"
		description="C3P0 pool"
		auth="Container"
		type="com.mchange.v2.c3p0.ComboPooledDataSource"

		acquireIncrement="3"
		maxPoolSize="10000"
		minPoolSize="3"
		maxIdleTime="30"

		maxConnectionAge="60"
		maxIdleTimeExcessConnections="10"

		testConnectionOnCheckout="true"
		preferredTestQuery="SELECT 1"

		acquireRetryAttempts="0"
		acquireRetryDelay="3000"
		breakAfterAcquireFailure="false"

		autoCommitOnClose="true"

		debugUnreturnedConnectionStackTraces="true"
		unreturnedConnectionTimeout="3600"

		user="user"
		password="password"
		jdbcUrl="jdbc:mysql://localhost:3306/database"
		driverClass="com.mysql.jdbc.Driver"
		factory="org.apache.naming.factory.BeanFactory" />

</Context>

Don't forget to add MySQL/MariaDB driver to {tomcat_dir}/lib.

Good luck ;-)

**Comment by dhirajgraycelltech** [comment]
hi, 

I have followed  your step but found same result, the above urls that you given has one unique url that is for lucid. And the steps given in idega website also same but with one different that you provide is not there. Can you tell me.. which are the main modules that i have to build first .. or you can tell me  if there is some url to hit ..i am hitting by context url.. tomcat showing project is deployed with running true. i have attached snapshot for this.
![a1](https://user-images.githubusercontent.com/38747709/39301927-8fed1cce-496e-11e8-998a-6656e310a76b.png)
![a2](https://user-images.githubusercontent.com/38747709/39301928-90351664-496e-11e8-9a51-98d0242246bf.png)

**Comment by L4p1n45** [comment]
Hello,

You have to deploy 'lucid' app, not idega-webapp-base. I already told you that you should use BRANCH_PLATFORM_5, not MASTER.

**Comment by dhirajgraycelltech** [comment]
hi, 

After taking clone from BRANCH_PLATFORM_5, i still unable to run the .war. 
I also have created ROOT.xml file in the conf/Catalina/localhost folder snapshot attached.
![t1](https://user-images.githubusercontent.com/38747709/39423807-4d7ab6aa-4c91-11e8-969e-a10237d1b8d1.png)

Please help!! :-)

**Comment by dhirajgraycelltech** [comment]
hi, actually it is, lucid 5.0.0 but still not working.
![t2](https://user-images.githubusercontent.com/38747709/39427521-a3410dcc-4ca1-11e8-93b7-bff381ba1474.png)
